---
- name: Setup windows host
  hosts: all
  vars:
    ansible_connection: ssh
    ansible_shell_type: cmd
  vars_prompt:
    - name: ansible_user
      prompt: Windows account username
      private: false
    - name: ansible_password
      prompt: Windows account password
  roles:
    - win-setup
