---
- name: Setup windows host
  hosts: all
  vars:
    ansible_connection: ssh
    ansible_shell_type: cmd
    ansible_user: sporzezinski
  tasks:
    - name: Ensure Chocolatey itself is installed, using community repo for the bootstrap
      win_chocolatey:
        name: chocolatey

    - name: Must have tools
      win_chocolatey:
        name:
          - vscode
          - powertoys
          - 7zip
          - firefox
          - docker-desktop
        state: present
