---
# tasks file for win-setup
- name: Ensure Chocolatey itself is installed, using community repo for the bootstrap
  win_chocolatey:
    name: chocolatey

- name: Upgrade installed packages
  win_chocolatey:
    name: all
    state: latest
  tags: upgrade-packages

- name: Install defined packages
  win_chocolatey:
    name: '{{ item }}'
    state: present
  loop: '{{ choco_packages }}'
  tags: install-packages

- name: Install fonts
  win_chocolatey:
    name: firacodenf
    state: present

- block:
  - include_tasks: powertoys.yml
  tags: powertoys

- block:
  - include_tasks: windows-terminal.yml
  tags: windows-terminal
