---
# tasks file for wsl-setup
- name: install packages necessary for setup
  become: true
  ansible.builtin.package:
    name: 
      - sshpass
      - libnss-mdns
      - snapd
- block:
  - include_tasks: shell.yml
  tags: shell
- name: Install aws-cli
  become: True
  community.general.snap:
    name: aws-cli
    classic: True
